/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.dsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.lilypond.dsl.DslPackage;
import org.xtext.lilypond.dsl.Es;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Es</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EsImpl extends OctaveImpl implements Es
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.ES;
  }

} //EsImpl
