/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.dsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.lilypond.dsl.DslPackage;
import org.xtext.lilypond.dsl.Is;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Is</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IsImpl extends OctaveImpl implements Is
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.IS;
  }

} //IsImpl
