/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.generator;

import com.google.common.collect.Iterables;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.lilypond.Transformer;
import org.xtext.lilypond.dsl.File;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class DslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    Iterable<File> _filter = Iterables.<File>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), File.class);
    for (final File file : _filter) {
      {
        Transformer transformer = new Transformer();
        LilyPondGenerator generator = new LilyPondGenerator();
        org.xtext.lilypond.lilyPond.File newFile = transformer.transformFile(file);
        generator.compile(newFile);
      }
    }
  }
}
