/*
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.lilypond.LilyPond.ui.internal.LilyPondActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LilyPondExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LilyPondActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LilyPondActivator activator = LilyPondActivator.getInstance();
		return activator != null ? activator.getInjector(LilyPondActivator.ORG_XTEXT_LILYPOND_LILYPOND) : null;
	}

}
