/*
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.lilypond.LilyPond.ui.internal.LilyPondActivator;

public class LilyPondUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LilyPondActivator.getInstance().getInjector("org.xtext.lilypond.LilyPond");
	}

}
