/*
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLilyPondScopeProvider extends DelegatingScopeProvider {
}
