/*
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.lilypond.LilyPondRuntimeModule;
import org.xtext.lilypond.LilyPondStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LilyPondIdeSetup extends LilyPondStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LilyPondRuntimeModule(), new LilyPondIdeModule()));
	}
	
}
