/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.lilyPond.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.lilypond.lilyPond.Commas;
import org.xtext.lilypond.lilyPond.LilyPondPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Commas</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CommasImpl extends OctaveRepImpl implements Commas
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CommasImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LilyPondPackage.Literals.COMMAS;
  }

} //CommasImpl
