/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.lilyPond.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.lilypond.lilyPond.LilyPondPackage;
import org.xtext.lilypond.lilyPond.Quotes;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Quotes</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class QuotesImpl extends OctaveRepImpl implements Quotes
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QuotesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LilyPondPackage.Literals.QUOTES;
  }

} //QuotesImpl
