/*
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.lilypond.Dsl.ui.internal.DslActivator;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.xtext.lilypond.Dsl");
	}

}
