/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.lilyPond;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Key</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.lilypond.lilyPond.LilyPondPackage#getKey()
 * @model
 * @generated
 */
public interface Key extends EObject
{
} // Key
