/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.lilyPond;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.lilypond.lilyPond.LilyPondFactory
 * @model kind="package"
 * @generated
 */
public interface LilyPondPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "lilyPond";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/lilypond/LilyPond";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "lilyPond";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LilyPondPackage eINSTANCE = org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.FileImpl <em>File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.FileImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getFile()
   * @generated
   */
  int FILE = 0;

  /**
   * The feature id for the '<em><b>Version</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE__VERSION = 0;

  /**
   * The feature id for the '<em><b>Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE__HEADER = 1;

  /**
   * The feature id for the '<em><b>Score</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE__SCORE = 2;

  /**
   * The number of structural features of the '<em>File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.VersionImpl <em>Version</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.VersionImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getVersion()
   * @generated
   */
  int VERSION = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION__VALUE = 0;

  /**
   * The number of structural features of the '<em>Version</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.HeaderImpl <em>Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.HeaderImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getHeader()
   * @generated
   */
  int HEADER = 2;

  /**
   * The feature id for the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__TITLE = 0;

  /**
   * The number of structural features of the '<em>Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.TitleImpl <em>Title</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.TitleImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getTitle()
   * @generated
   */
  int TITLE = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Title</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.ScoreImpl <em>Score</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.ScoreImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getScore()
   * @generated
   */
  int SCORE = 4;

  /**
   * The feature id for the '<em><b>Staff</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCORE__STAFF = 0;

  /**
   * The feature id for the '<em><b>Lyrics</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCORE__LYRICS = 1;

  /**
   * The number of structural features of the '<em>Score</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCORE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.StaffImpl <em>Staff</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.StaffImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getStaff()
   * @generated
   */
  int STAFF = 5;

  /**
   * The feature id for the '<em><b>Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAFF__KEY = 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAFF__TIME = 1;

  /**
   * The feature id for the '<em><b>Absolute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAFF__ABSOLUTE = 2;

  /**
   * The number of structural features of the '<em>Staff</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAFF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.KeyImpl <em>Key</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.KeyImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getKey()
   * @generated
   */
  int KEY = 6;

  /**
   * The number of structural features of the '<em>Key</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEY_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.TimeImpl <em>Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.TimeImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getTime()
   * @generated
   */
  int TIME = 7;

  /**
   * The number of structural features of the '<em>Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.AbsoluteImpl <em>Absolute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.AbsoluteImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getAbsolute()
   * @generated
   */
  int ABSOLUTE = 8;

  /**
   * The feature id for the '<em><b>Items</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSOLUTE__ITEMS = 0;

  /**
   * The number of structural features of the '<em>Absolute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSOLUTE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.NoteImpl <em>Note</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.NoteImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getNote()
   * @generated
   */
  int NOTE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Octave</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTE__OCTAVE = 1;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTE__DURATION = 2;

  /**
   * The number of structural features of the '<em>Note</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.OctaveRepImpl <em>Octave Rep</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.OctaveRepImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getOctaveRep()
   * @generated
   */
  int OCTAVE_REP = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCTAVE_REP__VALUE = 0;

  /**
   * The number of structural features of the '<em>Octave Rep</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCTAVE_REP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.LyricsImpl <em>Lyrics</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.LyricsImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getLyrics()
   * @generated
   */
  int LYRICS = 11;

  /**
   * The feature id for the '<em><b>Syllables</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LYRICS__SYLLABLES = 0;

  /**
   * The number of structural features of the '<em>Lyrics</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LYRICS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.QuotesImpl <em>Quotes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.QuotesImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getQuotes()
   * @generated
   */
  int QUOTES = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUOTES__VALUE = OCTAVE_REP__VALUE;

  /**
   * The number of structural features of the '<em>Quotes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUOTES_FEATURE_COUNT = OCTAVE_REP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.impl.CommasImpl <em>Commas</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.impl.CommasImpl
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getCommas()
   * @generated
   */
  int COMMAS = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAS__VALUE = OCTAVE_REP__VALUE;

  /**
   * The number of structural features of the '<em>Commas</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAS_FEATURE_COUNT = OCTAVE_REP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.lilypond.lilyPond.NoteName <em>Note Name</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lilypond.lilyPond.NoteName
   * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getNoteName()
   * @generated
   */
  int NOTE_NAME = 14;


  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.File <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>File</em>'.
   * @see org.xtext.lilypond.lilyPond.File
   * @generated
   */
  EClass getFile();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lilypond.lilyPond.File#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Version</em>'.
   * @see org.xtext.lilypond.lilyPond.File#getVersion()
   * @see #getFile()
   * @generated
   */
  EReference getFile_Version();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lilypond.lilyPond.File#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Header</em>'.
   * @see org.xtext.lilypond.lilyPond.File#getHeader()
   * @see #getFile()
   * @generated
   */
  EReference getFile_Header();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lilypond.lilyPond.File#getScore <em>Score</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Score</em>'.
   * @see org.xtext.lilypond.lilyPond.File#getScore()
   * @see #getFile()
   * @generated
   */
  EReference getFile_Score();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.Version <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Version</em>'.
   * @see org.xtext.lilypond.lilyPond.Version
   * @generated
   */
  EClass getVersion();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lilypond.lilyPond.Version#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.lilypond.lilyPond.Version#getValue()
   * @see #getVersion()
   * @generated
   */
  EAttribute getVersion_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.Header <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Header</em>'.
   * @see org.xtext.lilypond.lilyPond.Header
   * @generated
   */
  EClass getHeader();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lilypond.lilyPond.Header#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Title</em>'.
   * @see org.xtext.lilypond.lilyPond.Header#getTitle()
   * @see #getHeader()
   * @generated
   */
  EReference getHeader_Title();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.Title <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Title</em>'.
   * @see org.xtext.lilypond.lilyPond.Title
   * @generated
   */
  EClass getTitle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lilypond.lilyPond.Title#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.lilypond.lilyPond.Title#getValue()
   * @see #getTitle()
   * @generated
   */
  EAttribute getTitle_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.Score <em>Score</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Score</em>'.
   * @see org.xtext.lilypond.lilyPond.Score
   * @generated
   */
  EClass getScore();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lilypond.lilyPond.Score#getStaff <em>Staff</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Staff</em>'.
   * @see org.xtext.lilypond.lilyPond.Score#getStaff()
   * @see #getScore()
   * @generated
   */
  EReference getScore_Staff();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lilypond.lilyPond.Score#getLyrics <em>Lyrics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lyrics</em>'.
   * @see org.xtext.lilypond.lilyPond.Score#getLyrics()
   * @see #getScore()
   * @generated
   */
  EReference getScore_Lyrics();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.Staff <em>Staff</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Staff</em>'.
   * @see org.xtext.lilypond.lilyPond.Staff
   * @generated
   */
  EClass getStaff();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lilypond.lilyPond.Staff#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Key</em>'.
   * @see org.xtext.lilypond.lilyPond.Staff#getKey()
   * @see #getStaff()
   * @generated
   */
  EReference getStaff_Key();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lilypond.lilyPond.Staff#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see org.xtext.lilypond.lilyPond.Staff#getTime()
   * @see #getStaff()
   * @generated
   */
  EReference getStaff_Time();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lilypond.lilyPond.Staff#getAbsolute <em>Absolute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Absolute</em>'.
   * @see org.xtext.lilypond.lilyPond.Staff#getAbsolute()
   * @see #getStaff()
   * @generated
   */
  EReference getStaff_Absolute();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.Key <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Key</em>'.
   * @see org.xtext.lilypond.lilyPond.Key
   * @generated
   */
  EClass getKey();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.Time <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time</em>'.
   * @see org.xtext.lilypond.lilyPond.Time
   * @generated
   */
  EClass getTime();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.Absolute <em>Absolute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Absolute</em>'.
   * @see org.xtext.lilypond.lilyPond.Absolute
   * @generated
   */
  EClass getAbsolute();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.lilypond.lilyPond.Absolute#getItems <em>Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Items</em>'.
   * @see org.xtext.lilypond.lilyPond.Absolute#getItems()
   * @see #getAbsolute()
   * @generated
   */
  EReference getAbsolute_Items();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.Note <em>Note</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Note</em>'.
   * @see org.xtext.lilypond.lilyPond.Note
   * @generated
   */
  EClass getNote();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lilypond.lilyPond.Note#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.lilypond.lilyPond.Note#getName()
   * @see #getNote()
   * @generated
   */
  EAttribute getNote_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.lilypond.lilyPond.Note#getOctave <em>Octave</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Octave</em>'.
   * @see org.xtext.lilypond.lilyPond.Note#getOctave()
   * @see #getNote()
   * @generated
   */
  EReference getNote_Octave();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lilypond.lilyPond.Note#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.lilypond.lilyPond.Note#getDuration()
   * @see #getNote()
   * @generated
   */
  EAttribute getNote_Duration();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.OctaveRep <em>Octave Rep</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Octave Rep</em>'.
   * @see org.xtext.lilypond.lilyPond.OctaveRep
   * @generated
   */
  EClass getOctaveRep();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.lilypond.lilyPond.OctaveRep#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.xtext.lilypond.lilyPond.OctaveRep#getValue()
   * @see #getOctaveRep()
   * @generated
   */
  EAttribute getOctaveRep_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.Lyrics <em>Lyrics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lyrics</em>'.
   * @see org.xtext.lilypond.lilyPond.Lyrics
   * @generated
   */
  EClass getLyrics();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.lilypond.lilyPond.Lyrics#getSyllables <em>Syllables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Syllables</em>'.
   * @see org.xtext.lilypond.lilyPond.Lyrics#getSyllables()
   * @see #getLyrics()
   * @generated
   */
  EAttribute getLyrics_Syllables();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.Quotes <em>Quotes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Quotes</em>'.
   * @see org.xtext.lilypond.lilyPond.Quotes
   * @generated
   */
  EClass getQuotes();

  /**
   * Returns the meta object for class '{@link org.xtext.lilypond.lilyPond.Commas <em>Commas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Commas</em>'.
   * @see org.xtext.lilypond.lilyPond.Commas
   * @generated
   */
  EClass getCommas();

  /**
   * Returns the meta object for enum '{@link org.xtext.lilypond.lilyPond.NoteName <em>Note Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Note Name</em>'.
   * @see org.xtext.lilypond.lilyPond.NoteName
   * @generated
   */
  EEnum getNoteName();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LilyPondFactory getLilyPondFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.FileImpl <em>File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.FileImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getFile()
     * @generated
     */
    EClass FILE = eINSTANCE.getFile();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILE__VERSION = eINSTANCE.getFile_Version();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILE__HEADER = eINSTANCE.getFile_Header();

    /**
     * The meta object literal for the '<em><b>Score</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILE__SCORE = eINSTANCE.getFile_Score();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.VersionImpl <em>Version</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.VersionImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getVersion()
     * @generated
     */
    EClass VERSION = eINSTANCE.getVersion();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERSION__VALUE = eINSTANCE.getVersion_Value();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.HeaderImpl <em>Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.HeaderImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getHeader()
     * @generated
     */
    EClass HEADER = eINSTANCE.getHeader();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEADER__TITLE = eINSTANCE.getHeader_Title();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.TitleImpl <em>Title</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.TitleImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getTitle()
     * @generated
     */
    EClass TITLE = eINSTANCE.getTitle();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITLE__VALUE = eINSTANCE.getTitle_Value();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.ScoreImpl <em>Score</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.ScoreImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getScore()
     * @generated
     */
    EClass SCORE = eINSTANCE.getScore();

    /**
     * The meta object literal for the '<em><b>Staff</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCORE__STAFF = eINSTANCE.getScore_Staff();

    /**
     * The meta object literal for the '<em><b>Lyrics</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCORE__LYRICS = eINSTANCE.getScore_Lyrics();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.StaffImpl <em>Staff</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.StaffImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getStaff()
     * @generated
     */
    EClass STAFF = eINSTANCE.getStaff();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STAFF__KEY = eINSTANCE.getStaff_Key();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STAFF__TIME = eINSTANCE.getStaff_Time();

    /**
     * The meta object literal for the '<em><b>Absolute</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STAFF__ABSOLUTE = eINSTANCE.getStaff_Absolute();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.KeyImpl <em>Key</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.KeyImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getKey()
     * @generated
     */
    EClass KEY = eINSTANCE.getKey();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.TimeImpl <em>Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.TimeImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getTime()
     * @generated
     */
    EClass TIME = eINSTANCE.getTime();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.AbsoluteImpl <em>Absolute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.AbsoluteImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getAbsolute()
     * @generated
     */
    EClass ABSOLUTE = eINSTANCE.getAbsolute();

    /**
     * The meta object literal for the '<em><b>Items</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSOLUTE__ITEMS = eINSTANCE.getAbsolute_Items();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.NoteImpl <em>Note</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.NoteImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getNote()
     * @generated
     */
    EClass NOTE = eINSTANCE.getNote();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOTE__NAME = eINSTANCE.getNote_Name();

    /**
     * The meta object literal for the '<em><b>Octave</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOTE__OCTAVE = eINSTANCE.getNote_Octave();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOTE__DURATION = eINSTANCE.getNote_Duration();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.OctaveRepImpl <em>Octave Rep</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.OctaveRepImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getOctaveRep()
     * @generated
     */
    EClass OCTAVE_REP = eINSTANCE.getOctaveRep();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OCTAVE_REP__VALUE = eINSTANCE.getOctaveRep_Value();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.LyricsImpl <em>Lyrics</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.LyricsImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getLyrics()
     * @generated
     */
    EClass LYRICS = eINSTANCE.getLyrics();

    /**
     * The meta object literal for the '<em><b>Syllables</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LYRICS__SYLLABLES = eINSTANCE.getLyrics_Syllables();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.QuotesImpl <em>Quotes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.QuotesImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getQuotes()
     * @generated
     */
    EClass QUOTES = eINSTANCE.getQuotes();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.impl.CommasImpl <em>Commas</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.impl.CommasImpl
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getCommas()
     * @generated
     */
    EClass COMMAS = eINSTANCE.getCommas();

    /**
     * The meta object literal for the '{@link org.xtext.lilypond.lilyPond.NoteName <em>Note Name</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lilypond.lilyPond.NoteName
     * @see org.xtext.lilypond.lilyPond.impl.LilyPondPackageImpl#getNoteName()
     * @generated
     */
    EEnum NOTE_NAME = eINSTANCE.getNoteName();

  }

} //LilyPondPackage
