/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.lilyPond;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Octave Rep</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lilypond.lilyPond.OctaveRep#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.lilypond.lilyPond.LilyPondPackage#getOctaveRep()
 * @model
 * @generated
 */
public interface OctaveRep extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Character}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute list.
   * @see org.xtext.lilypond.lilyPond.LilyPondPackage#getOctaveRep_Value()
   * @model unique="false"
   * @generated
   */
  EList<Character> getValue();

} // OctaveRep
