/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.lilyPond;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Quotes</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.lilypond.lilyPond.LilyPondPackage#getQuotes()
 * @model
 * @generated
 */
public interface Quotes extends OctaveRep
{
} // Quotes
