/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.lilyPond;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Score</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lilypond.lilyPond.Score#getStaff <em>Staff</em>}</li>
 *   <li>{@link org.xtext.lilypond.lilyPond.Score#getLyrics <em>Lyrics</em>}</li>
 * </ul>
 *
 * @see org.xtext.lilypond.lilyPond.LilyPondPackage#getScore()
 * @model
 * @generated
 */
public interface Score extends EObject
{
  /**
   * Returns the value of the '<em><b>Staff</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Staff</em>' containment reference.
   * @see #setStaff(Staff)
   * @see org.xtext.lilypond.lilyPond.LilyPondPackage#getScore_Staff()
   * @model containment="true"
   * @generated
   */
  Staff getStaff();

  /**
   * Sets the value of the '{@link org.xtext.lilypond.lilyPond.Score#getStaff <em>Staff</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Staff</em>' containment reference.
   * @see #getStaff()
   * @generated
   */
  void setStaff(Staff value);

  /**
   * Returns the value of the '<em><b>Lyrics</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lyrics</em>' containment reference.
   * @see #setLyrics(Lyrics)
   * @see org.xtext.lilypond.lilyPond.LilyPondPackage#getScore_Lyrics()
   * @model containment="true"
   * @generated
   */
  Lyrics getLyrics();

  /**
   * Sets the value of the '{@link org.xtext.lilypond.lilyPond.Score#getLyrics <em>Lyrics</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lyrics</em>' containment reference.
   * @see #getLyrics()
   * @generated
   */
  void setLyrics(Lyrics value);

} // Score
