/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.lilyPond;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Staff</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lilypond.lilyPond.Staff#getKey <em>Key</em>}</li>
 *   <li>{@link org.xtext.lilypond.lilyPond.Staff#getTime <em>Time</em>}</li>
 *   <li>{@link org.xtext.lilypond.lilyPond.Staff#getAbsolute <em>Absolute</em>}</li>
 * </ul>
 *
 * @see org.xtext.lilypond.lilyPond.LilyPondPackage#getStaff()
 * @model
 * @generated
 */
public interface Staff extends EObject
{
  /**
   * Returns the value of the '<em><b>Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' containment reference.
   * @see #setKey(Key)
   * @see org.xtext.lilypond.lilyPond.LilyPondPackage#getStaff_Key()
   * @model containment="true"
   * @generated
   */
  Key getKey();

  /**
   * Sets the value of the '{@link org.xtext.lilypond.lilyPond.Staff#getKey <em>Key</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' containment reference.
   * @see #getKey()
   * @generated
   */
  void setKey(Key value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' containment reference.
   * @see #setTime(Time)
   * @see org.xtext.lilypond.lilyPond.LilyPondPackage#getStaff_Time()
   * @model containment="true"
   * @generated
   */
  Time getTime();

  /**
   * Sets the value of the '{@link org.xtext.lilypond.lilyPond.Staff#getTime <em>Time</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' containment reference.
   * @see #getTime()
   * @generated
   */
  void setTime(Time value);

  /**
   * Returns the value of the '<em><b>Absolute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Absolute</em>' containment reference.
   * @see #setAbsolute(Absolute)
   * @see org.xtext.lilypond.lilyPond.LilyPondPackage#getStaff_Absolute()
   * @model containment="true"
   * @generated
   */
  Absolute getAbsolute();

  /**
   * Sets the value of the '{@link org.xtext.lilypond.lilyPond.Staff#getAbsolute <em>Absolute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Absolute</em>' containment reference.
   * @see #getAbsolute()
   * @generated
   */
  void setAbsolute(Absolute value);

} // Staff
