/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Is</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.lilypond.dsl.DslPackage#getIs()
 * @model
 * @generated
 */
public interface Is extends Octave
{
} // Is
