/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Item</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.lilypond.dsl.DslPackage#getItem()
 * @model
 * @generated
 */
public interface Item extends EObject
{
} // Item
