/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Note Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lilypond.dsl.NoteItem#getNote <em>Note</em>}</li>
 * </ul>
 *
 * @see org.xtext.lilypond.dsl.DslPackage#getNoteItem()
 * @model
 * @generated
 */
public interface NoteItem extends Item
{
  /**
   * Returns the value of the '<em><b>Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Note</em>' containment reference.
   * @see #setNote(Note)
   * @see org.xtext.lilypond.dsl.DslPackage#getNoteItem_Note()
   * @model containment="true"
   * @generated
   */
  Note getNote();

  /**
   * Sets the value of the '{@link org.xtext.lilypond.dsl.NoteItem#getNote <em>Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Note</em>' containment reference.
   * @see #getNote()
   * @generated
   */
  void setNote(Note value);

} // NoteItem
