/**
 * generated by Xtext 2.25.0
 */
package org.xtext.lilypond.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Note</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lilypond.dsl.Note#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.lilypond.dsl.Note#getOctave <em>Octave</em>}</li>
 *   <li>{@link org.xtext.lilypond.dsl.Note#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.xtext.lilypond.dsl.Note#getSyllable <em>Syllable</em>}</li>
 * </ul>
 *
 * @see org.xtext.lilypond.dsl.DslPackage#getNote()
 * @model
 * @generated
 */
public interface Note extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.lilypond.dsl.NoteName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see org.xtext.lilypond.dsl.NoteName
   * @see #setName(NoteName)
   * @see org.xtext.lilypond.dsl.DslPackage#getNote_Name()
   * @model
   * @generated
   */
  NoteName getName();

  /**
   * Sets the value of the '{@link org.xtext.lilypond.dsl.Note#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see org.xtext.lilypond.dsl.NoteName
   * @see #getName()
   * @generated
   */
  void setName(NoteName value);

  /**
   * Returns the value of the '<em><b>Octave</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Octave</em>' containment reference.
   * @see #setOctave(Octave)
   * @see org.xtext.lilypond.dsl.DslPackage#getNote_Octave()
   * @model containment="true"
   * @generated
   */
  Octave getOctave();

  /**
   * Sets the value of the '{@link org.xtext.lilypond.dsl.Note#getOctave <em>Octave</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Octave</em>' containment reference.
   * @see #getOctave()
   * @generated
   */
  void setOctave(Octave value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(int)
   * @see org.xtext.lilypond.dsl.DslPackage#getNote_Duration()
   * @model
   * @generated
   */
  int getDuration();

  /**
   * Sets the value of the '{@link org.xtext.lilypond.dsl.Note#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(int value);

  /**
   * Returns the value of the '<em><b>Syllable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Syllable</em>' attribute.
   * @see #setSyllable(String)
   * @see org.xtext.lilypond.dsl.DslPackage#getNote_Syllable()
   * @model
   * @generated
   */
  String getSyllable();

  /**
   * Sets the value of the '{@link org.xtext.lilypond.dsl.Note#getSyllable <em>Syllable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Syllable</em>' attribute.
   * @see #getSyllable()
   * @generated
   */
  void setSyllable(String value);

} // Note
